# Esame del 21 Luglio 2025
### Francesco Cusenza - 0780292

In [ ]:
import numpy as np
from numpy.linalg import eig #codice esame 21 luglio

In [2]:
x = np.loadtxt("markov_chain.dat")
print(f'CATENA DI MARKOV:\n{x}')

states = np.array(x[:,1], dtype=int)
states = states - 1 # Cosi' partono da 0
N = 3 # Numero stati

CATENA DI MARKOV:
[[   0.    1.]
 [   1.    2.]
 [   2.    1.]
 ...
 [ 998.    1.]
 [ 999.    1.]
 [1000.    2.]]


In [ ]:
# Stima matrice di transizione
trans = np.zeros((N, N), dtype=int)

for t in range(len(states)-1):
    i = states[t]
    j = states[t+1]
    trans[i,j] += 1

P = trans / trans.sum(axis=1, keepdims=True) # Normalizzazione
print(f'MATRICE DI TRANSIZIONE:\n{P}')

MATRICE DI TRANSIZIONE:
[[0.506      0.242      0.252     ]
 [0.53846154 0.10121457 0.36032389]
 [0.44664032 0.40316206 0.15019763]]


In [4]:
# Calcolo di autovalori e auovettori
eigvals, eigvec = np.linalg.eig(P)
print(f'AUTOVALORI:\n{eigvals}\nAUTOVETTORI (colonne):\n{eigvec}')

AUTOVALORI:
[ 1.          0.01226365 -0.25485145]
AUTOVETTORI (colonne):
[[ 0.57735027  0.558766   -0.01282106]
 [ 0.57735027 -0.3640941  -0.70159328]
 [ 0.57735027 -0.74512821  0.71246228]]


In [5]:
sort_eigvals = np.sort(np.abs(eigvals))[::-1] # Mettono in ordine di modulo decrescente gli autovalori
print(f'AUTOVALORI ORDINATI:\n{sort_eigvals}')
print(f'Il secondo autovalore determina la convergenza alla stazionarietà')

AUTOVALORI ORDINATI:
[1.         0.25485145 0.01226365]
Il secondo autovalore determina la convergenza alla stazionarietà


In [6]:
# Determinazione stato stazionario
eigvalsT, eigvecT = np.linalg.eig(P.T) # Autovalori e autovettori della matrice trasposta, poichè pi_staz.T = P.T x pi_staz.T
stationarity = eigvecT[:, np.isclose(eigvalsT, 1)].real # Prendo la parte reale dell'autovettore associato ad 1
stationarity /= np.sum(stationarity) # Normalizzo l'autovettore associato ad 1
print(f'STAZIONARIETA\':\n{stationarity}')
print(f'L \'autovettore associato al primo autovalore (1) corrisponde alla distribuzione di probabilità in cui convergerà il processo stocastico\nSi nota che al passo t->inf gli stati non sono equiprobabili, poichè in la matrice di transizione è asimetrica, in particolare favorisce lo stato 1')

STAZIONARIETA':
[[0.49902367]
 [0.24788894]
 [0.2530874 ]]
L 'autovettore associato al primo autovalore (1) corrisponde alla distribuzione di probabilità in cui convergerà il processo stocastico
Si nota che al passo t->inf gli stati non sono equiprobabili, poichè in la matrice di transizione è asimetrica, in particolare favorisce lo stato 1


In [7]:
# Controllo sul vettore stazionarietà, deve valere anche pi_staz = pi_staz x P
print("Check pi_staz = pi_staz x P:", np.allclose(stationarity.T @ P, stationarity.T))
print("Check pi_staz.T = P.T x pi_staz.T:", np.allclose(P.T @ stationarity, stationarity))

Check pi_staz = pi_staz x P: True
Check pi_staz.T = P.T x pi_staz.T: True
