# Shuffling

In [43]:
import numpy as np
import random

In [64]:
np.random.seed(42)

#Float
x = np.random.uniform(1,101,10)

# Interi
x = np.random.randint(1,101,10, dtype=int) #[1,101) - 10 numeri

# Interi ordinati
x = np.arange(1,11)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]


### Bootstrap
E' uno shuffling senza rimpiazzi

In [65]:
np.random.seed(42)
n = len(x)
x_b = np.zeros(n)

for i in range(n):
    j = np.random.randint(0, n)
    x_b[i] = x[j]

# Oppure
# x_b = np.random.choice(x, size=n, replace=True)

print(x_b)

[ 7.  4.  8.  5.  7. 10.  3.  7.  8.  5.]


### Durstenfeld
E' un ottimizzazione del metodo Fisher-Yates. Parte dal primo elemento e va verso l'ultimo. Ad ogni iterazione scambia con un elemento compreso tra i ed N

In [58]:
np.random.seed(42)
n = len(x)
x_d = x.copy()

for i in range(0, n-1): # si ferma al penultimo
    j = np.random.randint(i,n) # i incluso
    temp = x_d[i]
    x_d[i] = x_d[j]
    x_d[j] = temp

print(x_d)

[ 7  5  1 10  3  4  2  6  8  9]


### Sattolo
Come Durstenfeld ma non consente ripetizioni

In [62]:
np.random.seed(42)
n = len(x)
x_s = x.copy()

for i in range(0, n-1):
    j = np.random.randint(i+1, n) # i non incluso
    temp = x_s[i]
    x_s[i] = x_s[j]
    x_s[j] = temp

print(x_s)

[ 8  6  1  7 10  4  5  2  3  9]


### Naive
Mescola casualmente, introduce un bias statistico

In [68]:
np.random.seed(42)
n = len(x)
x_n = x.copy()

for i in range(n):
    j = np.random.randint(0, n)
    temp = x_n[i]
    x_n[i] = x_n[j]
    x_n[j] = temp

print(x_n)

[ 7  4  2  5  6 10  3  9  8  1]
